config_path: "/home/programmer/master_project_experiments/07_12_2023/outputs/nerf_output/f3rm/2023-12-07_072525/config.yml"
model_path: "/home/programmer/master_project_experiments/07_12_2023/outputs/nerf_output/f3rm/2023-12-07_072525/nerfstudio_models/step-000029999.ckpt"
height: 200
width: 200
x: 0.2
y: 0
z: -0.2
x_angle: 0
y_angle: 1
